### ISSUE TITLE
Include list in coreconfig-softwareupdate-run.py

### ISSUE THREAD

**Issue by tep74** [UoE-macOS/jss#6]
It would be helpful to include a list the available updates in the jamfHelper dialog box.

**Comment by geoffklee** [comment]
How's this? It only seems to make sense to list updates that require a restart, since it's only when a restart is required that the user sees anything. 

Script:
https://github.com/UoE-macOS/jss/blob/i6/coreconfig-softwareupdate-run.py
Changes:
https://github.com/UoE-macOS/jss/compare/master...i6

Actually this behaviour seems wrong - if an update requires a restart, we don't install any of them until the user agrees to restart. Which isn't really what we want to be doing. I'd better open an bug (done).

**Comment by tep74** [comment]
Yes, only for updates that require a restart, because the others don't even prompt a dialog box. The reason I'd like the list of what's available is for users who THINK their systems are up to date, but still have updates available - like the 10.13.2 supplemental update.

**Comment by tep74** [comment]
Works perfectly for me - restarted and updated with list!

**Comment by geoffklee** [comment]
I've opened #7 to look at re-working the logic so that non-reboot-requiring updates get installed *before* prompting the user.
